/**
 * 300개 성격 형용사 - 6대 카테고리
 * id, category, label 구조의 JSON 배열
 */

export type TraitCategory = "emotional" | "interpersonal" | "workStyle" | "cognitive" | "selfConcept" | "values";

export type Trait = {
  id: string;
  category: TraitCategory;
  label: string;
};

export const TRAITS: Trait[] = [
  // 1. 정서 (emotional)
  { id: "emotional-01", category: "emotional", label: "명랑한" },
  { id: "emotional-02", category: "emotional", label: "쾌활한" },
  { id: "emotional-03", category: "emotional", label: "유쾌한" },
  { id: "emotional-04", category: "emotional", label: "발랄한" },
  { id: "emotional-05", category: "emotional", label: "낙천적인" },
  { id: "emotional-06", category: "emotional", label: "긍정적인" },
  { id: "emotional-07", category: "emotional", label: "희망적인" },
  { id: "emotional-08", category: "emotional", label: "태평한" },
  { id: "emotional-09", category: "emotional", label: "편안한" },
  { id: "emotional-10", category: "emotional", label: "안정적인" },
  { id: "emotional-11", category: "emotional", label: "차분한" },
  { id: "emotional-12", category: "emotional", label: "침착한" },
  { id: "emotional-13", category: "emotional", label: "온화한" },
  { id: "emotional-14", category: "emotional", label: "평온한" },
  { id: "emotional-15", category: "emotional", label: "느긋한" },
  { id: "emotional-16", category: "emotional", label: "포근한" },
  { id: "emotional-17", category: "emotional", label: "정이 많은" },
  { id: "emotional-18", category: "emotional", label: "다정한" },
  { id: "emotional-19", category: "emotional", label: "따뜻한" },
  { id: "emotional-20", category: "emotional", label: "자상한" },
  { id: "emotional-21", category: "emotional", label: "감수성이 풍부한" },
  { id: "emotional-22", category: "emotional", label: "감정이입을 잘 하는" },
  { id: "emotional-23", category: "emotional", label: "눈물이 많은" },
  { id: "emotional-24", category: "emotional", label: "섬세한" },
  { id: "emotional-25", category: "emotional", label: "예민한" },
  { id: "emotional-26", category: "emotional", label: "불안한" },
  { id: "emotional-27", category: "emotional", label: "걱정이 많은" },
  { id: "emotional-28", category: "emotional", label: "긴장하는" },
  { id: "emotional-29", category: "emotional", label: "신경질적인" },
  { id: "emotional-30", category: "emotional", label: "과민한" },
  { id: "emotional-31", category: "emotional", label: "기복이 큰" },
  { id: "emotional-32", category: "emotional", label: "쉽게 들뜨는" },
  { id: "emotional-33", category: "emotional", label: "쉽게 실망하는" },
  { id: "emotional-34", category: "emotional", label: "상처를 잘 받는" },
  { id: "emotional-35", category: "emotional", label: "비관적인" },
  { id: "emotional-36", category: "emotional", label: "우울한" },
  { id: "emotional-37", category: "emotional", label: "침울한" },
  { id: "emotional-38", category: "emotional", label: "냉소적인" },
  { id: "emotional-39", category: "emotional", label: "회의적인" },
  { id: "emotional-40", category: "emotional", label: "짜증을 잘 내는" },
  { id: "emotional-41", category: "emotional", label: "분노를 잘 표출하는" },
  { id: "emotional-42", category: "emotional", label: "다혈질인" },
  { id: "emotional-43", category: "emotional", label: "욱하는" },
  { id: "emotional-44", category: "emotional", label: "자제력이 강한" },
  { id: "emotional-45", category: "emotional", label: "감정을 잘 숨기는" },
  { id: "emotional-46", category: "emotional", label: "표정이 풍부한" },
  { id: "emotional-47", category: "emotional", label: "표정이 잘 드러나지 않는" },
  { id: "emotional-48", category: "emotional", label: "스스로를 잘 위로하는" },
  { id: "emotional-49", category: "emotional", label: "감정을 잘 표현하는" },
  { id: "emotional-50", category: "emotional", label: "감정을 말로 풀기 어려워하는" },

  // 2. 관계 (interpersonal)
  { id: "interpersonal-01", category: "interpersonal", label: "사교적인" },
  { id: "interpersonal-02", category: "interpersonal", label: "붙임성 좋은" },
  { id: "interpersonal-03", category: "interpersonal", label: "외향적인" },
  { id: "interpersonal-04", category: "interpersonal", label: "사람 만나는 것을 좋아하는" },
  { id: "interpersonal-05", category: "interpersonal", label: "새로운 사람에게 먼저 다가가는" },
  { id: "interpersonal-06", category: "interpersonal", label: "말이 많은" },
  { id: "interpersonal-07", category: "interpersonal", label: "분위기 메이커인" },
  { id: "interpersonal-08", category: "interpersonal", label: "유머러스한" },
  { id: "interpersonal-09", category: "interpersonal", label: "장난기가 많은" },
  { id: "interpersonal-10", category: "interpersonal", label: "재치 있는" },
  { id: "interpersonal-11", category: "interpersonal", label: "공감 능력이 뛰어난" },
  { id: "interpersonal-12", category: "interpersonal", label: "배려심이 깊은" },
  { id: "interpersonal-13", category: "interpersonal", label: "이해심이 많은" },
  { id: "interpersonal-14", category: "interpersonal", label: "상대를 잘 칭찬하는" },
  { id: "interpersonal-15", category: "interpersonal", label: "경청을 잘 하는" },
  { id: "interpersonal-16", category: "interpersonal", label: "다른 사람 얘기를 끌어내는 데 능숙한" },
  { id: "interpersonal-17", category: "interpersonal", label: "협조적인" },
  { id: "interpersonal-18", category: "interpersonal", label: "팀 플레이를 잘 하는" },
  { id: "interpersonal-19", category: "interpersonal", label: "온화하게 조율하는" },
  { id: "interpersonal-20", category: "interpersonal", label: "중재를 잘 하는" },
  { id: "interpersonal-21", category: "interpersonal", label: "갈등을 피하려는" },
  { id: "interpersonal-22", category: "interpersonal", label: "상대를 배려하느라 자기 의견을 미루는" },
  { id: "interpersonal-23", category: "interpersonal", label: "예의를 중시하는" },
  { id: "interpersonal-24", category: "interpersonal", label: "예절에 민감한" },
  { id: "interpersonal-25", category: "interpersonal", label: "예의 바른" },
  { id: "interpersonal-26", category: "interpersonal", label: "무례함에 민감한" },
  { id: "interpersonal-27", category: "interpersonal", label: "솔직하게 말하는" },
  { id: "interpersonal-28", category: "interpersonal", label: "직설적인" },
  { id: "interpersonal-29", category: "interpersonal", label: "거침없이 말하는" },
  { id: "interpersonal-30", category: "interpersonal", label: "비판을 서슴지 않는" },
  { id: "interpersonal-31", category: "interpersonal", label: "냉정하게 지적하는" },
  { id: "interpersonal-32", category: "interpersonal", label: "타인의 시선을 많이 의식하는" },
  { id: "interpersonal-33", category: "interpersonal", label: "평판을 중요하게 여기는" },
  { id: "interpersonal-34", category: "interpersonal", label: "인정 욕구가 강한" },
  { id: "interpersonal-35", category: "interpersonal", label: "눈치를 많이 보는" },
  { id: "interpersonal-36", category: "interpersonal", label: "거절을 어려워하는" },
  { id: "interpersonal-37", category: "interpersonal", label: "부탁을 잘 들어주는" },
  { id: "interpersonal-38", category: "interpersonal", label: "남에게 의지하는 경향이 있는" },
  { id: "interpersonal-39", category: "interpersonal", label: "혼자 있기를 좋아하는" },
  { id: "interpersonal-40", category: "interpersonal", label: "내성적인" },
  { id: "interpersonal-41", category: "interpersonal", label: "과묵한" },
  { id: "interpersonal-42", category: "interpersonal", label: "조용한" },
  { id: "interpersonal-43", category: "interpersonal", label: "소수의 깊은 관계를 선호하는" },
  { id: "interpersonal-44", category: "interpersonal", label: "타인에게 마음을 여는 데 시간이 걸리는" },
  { id: "interpersonal-45", category: "interpersonal", label: "사람을 잘 믿지 않는" },
  { id: "interpersonal-46", category: "interpersonal", label: "경계심이 강한" },
  { id: "interpersonal-47", category: "interpersonal", label: "경쟁심이 강한" },
  { id: "interpersonal-48", category: "interpersonal", label: "상대를 이기고 싶어하는" },
  { id: "interpersonal-49", category: "interpersonal", label: "리더십을 발휘하는" },
  { id: "interpersonal-50", category: "interpersonal", label: "책임을 맡기를 선호하는" },

  // 3. 일 (workStyle)
  { id: "workStyle-01", category: "workStyle", label: "성실한" },
  { id: "workStyle-02", category: "workStyle", label: "부지런한" },
  { id: "workStyle-03", category: "workStyle", label: "책임감이 강한" },
  { id: "workStyle-04", category: "workStyle", label: "맡은 일은 끝까지 하는" },
  { id: "workStyle-05", category: "workStyle", label: "마감을 잘 지키는" },
  { id: "workStyle-06", category: "workStyle", label: "자발적으로 움직이는" },
  { id: "workStyle-07", category: "workStyle", label: "목표지향적인" },
  { id: "workStyle-08", category: "workStyle", label: "성취욕이 강한" },
  { id: "workStyle-09", category: "workStyle", label: "야망이 있는" },
  { id: "workStyle-10", category: "workStyle", label: "경쟁적으로 일하는" },
  { id: "workStyle-11", category: "workStyle", label: "업무에 몰입하는" },
  { id: "workStyle-12", category: "workStyle", label: "집중력이 높은" },
  { id: "workStyle-13", category: "workStyle", label: "끈기가 있는" },
  { id: "workStyle-14", category: "workStyle", label: "쉽게 포기하지 않는" },
  { id: "workStyle-15", category: "workStyle", label: "인내심이 강한" },
  { id: "workStyle-16", category: "workStyle", label: "반복 작업도 잘 해내는" },
  { id: "workStyle-17", category: "workStyle", label: "루틴을 잘 지키는" },
  { id: "workStyle-18", category: "workStyle", label: "계획적인" },
  { id: "workStyle-19", category: "workStyle", label: "체계적인" },
  { id: "workStyle-20", category: "workStyle", label: "조직적인" },
  { id: "workStyle-21", category: "workStyle", label: "꼼꼼한" },
  { id: "workStyle-22", category: "workStyle", label: "디테일에 강한" },
  { id: "workStyle-23", category: "workStyle", label: "실수를 줄이려고 노력하는" },
  { id: "workStyle-24", category: "workStyle", label: "체크 리스트를 잘 활용하는" },
  { id: "workStyle-25", category: "workStyle", label: "미리 준비하는" },
  { id: "workStyle-26", category: "workStyle", label: "정리정돈을 잘 하는" },
  { id: "workStyle-27", category: "workStyle", label: "깔끔한" },
  { id: "workStyle-28", category: "workStyle", label: "서류·파일 정리가 잘 된" },
  { id: "workStyle-29", category: "workStyle", label: "일정 관리를 잘 하는" },
  { id: "workStyle-30", category: "workStyle", label: "시간 약속을 잘 지키는" },
  { id: "workStyle-31", category: "workStyle", label: "지각을 거의 하지 않는" },
  { id: "workStyle-32", category: "workStyle", label: "우선순위를 잘 정하는" },
  { id: "workStyle-33", category: "workStyle", label: "효율을 따지는" },
  { id: "workStyle-34", category: "workStyle", label: "실용적인 방식으로 일하는" },
  { id: "workStyle-35", category: "workStyle", label: "즉흥적인" },
  { id: "workStyle-36", category: "workStyle", label: "충동적으로 시작하는" },
  { id: "workStyle-37", category: "workStyle", label: "기분 따라 일하는" },
  { id: "workStyle-38", category: "workStyle", label: "마감 직전에 몰아서 하는" },
  { id: "workStyle-39", category: "workStyle", label: "게으른 편인" },
  { id: "workStyle-40", category: "workStyle", label: "일을 쉽게 미루는" },
  { id: "workStyle-41", category: "workStyle", label: "집중이 자주 흐트러지는" },
  { id: "workStyle-42", category: "workStyle", label: "꾸준하지 못한" },
  { id: "workStyle-43", category: "workStyle", label: "시작은 잘하지만 끝을 못 보는" },
  { id: "workStyle-44", category: "workStyle", label: "완벽주의적인" },
  { id: "workStyle-45", category: "workStyle", label: "결과에 예민한" },
  { id: "workStyle-46", category: "workStyle", label: "실수에 과하게 집착하는" },
  { id: "workStyle-47", category: "workStyle", label: "자신에게 엄격한" },
  { id: "workStyle-48", category: "workStyle", label: "남의 일까지 떠맡는" },
  { id: "workStyle-49", category: "workStyle", label: "일과 삶의 균형을 중시하는" },
  { id: "workStyle-50", category: "workStyle", label: "근면한" },

  // 4. 사고방식 (cognitive)
  { id: "cognitive-01", category: "cognitive", label: "논리적인" },
  { id: "cognitive-02", category: "cognitive", label: "분석적인" },
  { id: "cognitive-03", category: "cognitive", label: "합리적인" },
  { id: "cognitive-04", category: "cognitive", label: "근거 중심으로 생각하는" },
  { id: "cognitive-05", category: "cognitive", label: "원인·결과를 따지는" },
  { id: "cognitive-06", category: "cognitive", label: "구조적으로 정리하는" },
  { id: "cognitive-07", category: "cognitive", label: "머리가 빠른" },
  { id: "cognitive-08", category: "cognitive", label: "이해가 빠른" },
  { id: "cognitive-09", category: "cognitive", label: "패턴을 잘 파악하는" },
  { id: "cognitive-10", category: "cognitive", label: "전략적으로 생각하는" },
  { id: "cognitive-11", category: "cognitive", label: "계획을 세우고 시나리오를 그리는" },
  { id: "cognitive-12", category: "cognitive", label: "장기적인 관점을 갖는" },
  { id: "cognitive-13", category: "cognitive", label: "데이터·사실을 중시하는" },
  { id: "cognitive-14", category: "cognitive", label: "감정보다 이성을 중시하는" },
  { id: "cognitive-15", category: "cognitive", label: "이론을 좋아하는" },
  { id: "cognitive-16", category: "cognitive", label: "개념화하는 능력이 좋은" },
  { id: "cognitive-17", category: "cognitive", label: "창의적인" },
  { id: "cognitive-18", category: "cognitive", label: "독창적인" },
  { id: "cognitive-19", category: "cognitive", label: "아이디어가 풍부한" },
  { id: "cognitive-20", category: "cognitive", label: "새로운 관점에서 보는" },
  { id: "cognitive-21", category: "cognitive", label: "상상력이 풍부한" },
  { id: "cognitive-22", category: "cognitive", label: "비유와 상징을 잘 쓰는" },
  { id: "cognitive-23", category: "cognitive", label: "예술적 감수성이 있는" },
  { id: "cognitive-24", category: "cognitive", label: "직관적인" },
  { id: "cognitive-25", category: "cognitive", label: "느낌을 믿고 결정하는" },
  { id: "cognitive-26", category: "cognitive", label: "전체 분위기로 판단하는" },
  { id: "cognitive-27", category: "cognitive", label: "세부보다는 큰 그림을 보는" },
  { id: "cognitive-28", category: "cognitive", label: "통찰력이 있는" },
  { id: "cognitive-29", category: "cognitive", label: "눈치가 빠른" },
  { id: "cognitive-30", category: "cognitive", label: "사람의 속마음을 잘 읽는" },
  { id: "cognitive-31", category: "cognitive", label: "복잡하게 생각하는 경향이 있는" },
  { id: "cognitive-32", category: "cognitive", label: "걱정이 많아 머릿속이 복잡한" },
  { id: "cognitive-33", category: "cognitive", label: "사소한 것도 많이 고민하는" },
  { id: "cognitive-34", category: "cognitive", label: "우유부단한" },
  { id: "cognitive-35", category: "cognitive", label: "결정을 미루는" },
  { id: "cognitive-36", category: "cognitive", label: "선택 상황을 어려워하는" },
  { id: "cognitive-37", category: "cognitive", label: "단순하게 생각하려고 노력하는" },
  { id: "cognitive-38", category: "cognitive", label: "직관적으로 선택해도 후회가 적은" },
  { id: "cognitive-39", category: "cognitive", label: "보수적인 사고를 가진" },
  { id: "cognitive-40", category: "cognitive", label: "전통을 중시하는" },
  { id: "cognitive-41", category: "cognitive", label: "변화에 조심스러운" },
  { id: "cognitive-42", category: "cognitive", label: "위험을 피하려는" },
  { id: "cognitive-43", category: "cognitive", label: "진보적인 사고를 가진" },
  { id: "cognitive-44", category: "cognitive", label: "새로운 제도·방식을 환영하는" },
  { id: "cognitive-45", category: "cognitive", label: "규칙의 이유를 따지는" },
  { id: "cognitive-46", category: "cognitive", label: "호기심이 많은" },
  { id: "cognitive-47", category: "cognitive", label: "질문을 많이 하는" },
  { id: "cognitive-48", category: "cognitive", label: "탐구심이 강한" },
  { id: "cognitive-49", category: "cognitive", label: "배우는 것을 즐기는" },
  { id: "cognitive-50", category: "cognitive", label: "자기 분야를 깊게 파고드는" },

  // 5. 자아 (selfConcept)
  { id: "selfConcept-01", category: "selfConcept", label: "자존감이 높은" },
  { id: "selfConcept-02", category: "selfConcept", label: "스스로를 긍정적으로 보는" },
  { id: "selfConcept-03", category: "selfConcept", label: "자신감이 넘치는" },
  { id: "selfConcept-04", category: "selfConcept", label: "당당한" },
  { id: "selfConcept-05", category: "selfConcept", label: "자기 주장이 분명한" },
  { id: "selfConcept-06", category: "selfConcept", label: "의견을 명확히 말하는" },
  { id: "selfConcept-07", category: "selfConcept", label: "주체적인" },
  { id: "selfConcept-08", category: "selfConcept", label: "스스로 선택하는 것을 선호하는" },
  { id: "selfConcept-09", category: "selfConcept", label: "책임을 자기 몫으로 받아들이는" },
  { id: "selfConcept-10", category: "selfConcept", label: "남 탓을 잘 하지 않는" },
  { id: "selfConcept-11", category: "selfConcept", label: "자존감이 낮은" },
  { id: "selfConcept-12", category: "selfConcept", label: "스스로를 자주 깎아내리는" },
  { id: "selfConcept-13", category: "selfConcept", label: "비교를 많이 하는" },
  { id: "selfConcept-14", category: "selfConcept", label: "인정받지 못할까 불안한" },
  { id: "selfConcept-15", category: "selfConcept", label: "실패를 과하게 두려워하는" },
  { id: "selfConcept-16", category: "selfConcept", label: "완벽하지 않으면 시작하기 어려워하는" },
  { id: "selfConcept-17", category: "selfConcept", label: "자기 비판이 강한" },
  { id: "selfConcept-18", category: "selfConcept", label: "후회를 자주 하는" },
  { id: "selfConcept-19", category: "selfConcept", label: "자기 돌봄에 신경 쓰는" },
  { id: "selfConcept-20", category: "selfConcept", label: "휴식의 필요를 잘 인식하는" },
  { id: "selfConcept-21", category: "selfConcept", label: "스트레스 관리에 관심 있는" },
  { id: "selfConcept-22", category: "selfConcept", label: "감정을 스스로 정리하는 능력이 있는" },
  { id: "selfConcept-23", category: "selfConcept", label: "일기를 쓰거나 기록으로 정리하는" },
  { id: "selfConcept-24", category: "selfConcept", label: "자기 성찰적인" },
  { id: "selfConcept-25", category: "selfConcept", label: "스스로를 돌아보는 시간을 갖는" },
  { id: "selfConcept-26", category: "selfConcept", label: "자신의 패턴을 분석하는" },
  { id: "selfConcept-27", category: "selfConcept", label: "성장하려는 의지가 강한" },
  { id: "selfConcept-28", category: "selfConcept", label: "피드백을 받아들이려는 태도가 있는" },
  { id: "selfConcept-29", category: "selfConcept", label: "실수를 학습 기회로 보는" },
  { id: "selfConcept-30", category: "selfConcept", label: "변화하려는 노력이 있는" },
  { id: "selfConcept-31", category: "selfConcept", label: "고집이 센" },
  { id: "selfConcept-32", category: "selfConcept", label: "생각을 잘 바꾸지 않는" },
  { id: "selfConcept-33", category: "selfConcept", label: "내가 맞다고 믿는 편인" },
  { id: "selfConcept-34", category: "selfConcept", label: "타협을 잘 안 하는" },
  { id: "selfConcept-35", category: "selfConcept", label: "유연한" },
  { id: "selfConcept-36", category: "selfConcept", label: "상황에 따라 태도를 조절하는" },
  { id: "selfConcept-37", category: "selfConcept", label: "상대 입장에서 생각해보는" },
  { id: "selfConcept-38", category: "selfConcept", label: "완벽하지 않아도 괜찮다고 여기는" },
  { id: "selfConcept-39", category: "selfConcept", label: "충동을 억제하는 힘이 강한" },
  { id: "selfConcept-40", category: "selfConcept", label: "참을성이 있는" },
  { id: "selfConcept-41", category: "selfConcept", label: "순간 감정에 휘둘리지 않으려는" },
  { id: "selfConcept-42", category: "selfConcept", label: "말하기 전에 한 번 더 생각하는" },
  { id: "selfConcept-43", category: "selfConcept", label: "감정에 쉽게 휩쓸리는" },
  { id: "selfConcept-44", category: "selfConcept", label: "순간적으로 행동해버리는" },
  { id: "selfConcept-45", category: "selfConcept", label: "후에 후회하는 경우가 많은" },
  { id: "selfConcept-46", category: "selfConcept", label: "금방 열정이 솟고 금방 식는" },
  { id: "selfConcept-47", category: "selfConcept", label: "루틴·습관을 통해 자신을 관리하는" },
  { id: "selfConcept-48", category: "selfConcept", label: "목표를 쪼개서 실천하는" },
  { id: "selfConcept-49", category: "selfConcept", label: "자기 계발 콘텐츠를 즐겨 보는" },

  // 6. 가치관 (values)
  { id: "values-01", category: "values", label: "도덕성을 중시하는" },
  { id: "values-02", category: "values", label: "정직함을 중요하게 여기는" },
  { id: "values-03", category: "values", label: "약속을 지키는 편인" },
  { id: "values-04", category: "values", label: "신뢰를 소중히 여기는" },
  { id: "values-05", category: "values", label: "약자에게 공감하는" },
  { id: "values-06", category: "values", label: "불공정을 참기 어려워하는" },
  { id: "values-07", category: "values", label: "규칙을 잘 지키는" },
  { id: "values-08", category: "values", label: "법·제도를 존중하는" },
  { id: "values-09", category: "values", label: "질서를 중시하는" },
  { id: "values-10", category: "values", label: "정의감이 강한" },
  { id: "values-11", category: "values", label: "현실적인" },
  { id: "values-12", category: "values", label: "실용적인" },
  { id: "values-13", category: "values", label: "계산을 잘 하는" },
  { id: "values-14", category: "values", label: "비용·효용을 따지는" },
  { id: "values-15", category: "values", label: "효율을 우선하는" },
  { id: "values-16", category: "values", label: "이상주의적인" },
  { id: "values-17", category: "values", label: "의미와 가치를 중시하는" },
  { id: "values-18", category: "values", label: "사명감을 가지고 행동하는" },
  { id: "values-19", category: "values", label: "사회적 영향력을 신경 쓰는" },
  { id: "values-20", category: "values", label: "공동체를 중요하게 여기는" },
  { id: "values-21", category: "values", label: "가족 중심적인" },
  { id: "values-22", category: "values", label: "친구 관계를 중요하게 여기는" },
  { id: "values-23", category: "values", label: "인간관계에 시간을 많이 쓰는" },
  { id: "values-24", category: "values", label: "혼자만의 시간을 소중히 여기는" },
  { id: "values-25", category: "values", label: "미니멀리스트 성향이 있는" },
  { id: "values-26", category: "values", label: "물건을 잘 안 사는 편인" },
  { id: "values-27", category: "values", label: "심플함을 선호하는" },
  { id: "values-28", category: "values", label: "수집 욕구가 있는" },
  { id: "values-29", category: "values", label: "취미에 돈을 아끼지 않는" },
  { id: "values-30", category: "values", label: "감각적인" },
  { id: "values-31", category: "values", label: "미적 감각이 뛰어난" },
  { id: "values-32", category: "values", label: "인테리어·패션에 관심 있는" },
  { id: "values-33", category: "values", label: "디테일한 분위기를 신경 쓰는" },
  { id: "values-34", category: "values", label: "건강을 중시하는" },
  { id: "values-35", category: "values", label: "운동 습관을 유지하려는" },
  { id: "values-36", category: "values", label: "식습관에 신경 쓰는" },
  { id: "values-37", category: "values", label: "규칙적인 생활을 추구하는" },
  { id: "values-38", category: "values", label: "즉흥적인 경험을 중시하는" },
  { id: "values-39", category: "values", label: "여행을 좋아하는" },
  { id: "values-40", category: "values", label: "새로운 장소를 탐험하는" },
  { id: "values-41", category: "values", label: "모험심이 있는" },
  { id: "values-42", category: "values", label: "안전을 우선하는" },
  { id: "values-43", category: "values", label: "안정된 직장·환경을 선호하는" },
  { id: "values-44", category: "values", label: "리스크를 피하는" },
  { id: "values-45", category: "values", label: "경제적 안정에 민감한" },
  { id: "values-46", category: "values", label: "여가를 중요하게 여기는" },
  { id: "values-47", category: "values", label: "취미 활동에 몰입하는" },
  { id: "values-48", category: "values", label: "일보다 삶의 질을 중시하는" },
  { id: "values-49", category: "values", label: "성과보다 과정의 즐거움을 중시하는" },
  { id: "values-50", category: "values", label: "배움과 성장을 평생 가치로 여기는" },
];

/** 카테고리 한글 라벨 */
export const TRAIT_CATEGORY_LABELS: Record<TraitCategory, string> = {
  emotional: "정서",
  interpersonal: "관계",
  workStyle: "일",
  cognitive: "사고방식",
  selfConcept: "자아",
  values: "가치관",
};

/** 카테고리 표시 순서 */
export const TRAIT_CATEGORY_ORDER: TraitCategory[] = [
  "emotional",
  "interpersonal",
  "workStyle",
  "cognitive",
  "selfConcept",
  "values",
];
